{% set version = "4.6.0" %}
package:
    name: nco
    version: {{ version }}

source:
    fn: nco-{{ version }}.tar.gz
    url: https://github.com/nco/nco/archive/{{ version }}.tar.gz
    sha256: 2ebeec6456255d363e9f5ef92d45cd809c058495d2c3920de3eacda5098986a9

build:
    number: 3
    skip: True  # [win]

requirements:
    build:
        - gsl
        - antlr
        - curl
        - zlib 1.2.*
        - hdf5 1.8.17|1.8.17.*
        - libnetcdf 4.4.*
        - udunits2
        - expat
        - krb5
        - texinfo
        - bison
        - flex
        - m4
    run:
        - gsl
        - hdf5 1.8.17|1.8.17.*
        - libnetcdf 4.4.*
        - udunits2
        - expat
        - libgcc
        - esmf

test:
    commands:
        - ncks --help
        - ncap2 --help
        - conda inspect linkages -n _test nco  # [linux]

about:
    home: http://nco.sourceforge.net/
    license: GPL-3.0
    summary: Suite of programs for manipulating NetCDF/HDF4 files

extra:
    recipe-maintainers:
        - ocefpaf
        - kwilcox
